apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik
  name: traefik-web
spec:
  ports:
  - port: 8000
    protocol: TCP
    nodePort: 30007
    targetPort: 8000
  selector:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik
  type: NodePort
