kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: apollo11
  name: mongodb-pvc
spec:
  storageClassName: mongodb-storageclass
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi