apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apollo11
  labels:
    app: fastapi
  name: fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - image: darraul/apollo11-fastapi:2.0
        name: fastapi
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 3000
      #   env:
      #   - name: MAIN_FILE_NAME
      #     valueFrom:
      #       configMapKeyRef:
      #         name: fastapi
      #         key: main_file_name
      #   - name: MAIN_FUNCTION_NAME
      #     valueFrom:
      #       configMapKeyRef:
      #         name: fastapi
      #         key: main_function_name
      #   livenessProbe:
      #     httpGet:
      #       path: /health
      #       port: 3000
      #     initialDelaySeconds: 3
      #     periodSeconds: 3
      #     timeoutSeconds: 5
      #     successThreshold: 1
      #     failureThreshold: 3
      #   readinessProbe:
      #     tcpSocket:
      #       port: 3000
      #     initialDelaySeconds: 5
      #     periodSeconds: 10
      #     timeoutSeconds: 5
      #     successThreshold: 2
      #     failureThreshold: 3
      #   startupProbe:
      #     httpGet:
      #       path: /startup
      #       port: 3000
      #     failureThreshold: 30
      #     periodSeconds: 10
      #     timeoutSeconds: 5
      #     successThreshold: 1
      #     failureThreshold: 3
      #   volumeMounts:
      #   - name: fastapi-secret
      #     mountPath: "/etc/secrets"
      #     readOnly: true
      # volumes:
      # - name: fastapi-secret
      #   secret:
      #     secretName: fastapi
      #     items:
      #     - key: name
      #       path: fastapi-name
      # initContainers:
      # - name: init-myservice
      #   image: busybox:1.28
      #   command: ['sh', '-c', "sleep 15"]
      restartPolicy: "Always"

