apiVersion: v1
kind: Service
metadata:
  namespace: apollo11
  app: fastapi
spec:
  type: NodePort
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30097